#include "extrah/extern.h"
#include <QDebug>

int Extern::choisen=0;//临时
QString Extern::loginername="z";//临时用户名
QMap<QString,int> Extern::allloginer;
int Extern::progress_value=0;
int Extern::loginfocus=0;
int Extern::check_desk_choosen=0;
int Extern::customer_to_server=2;
QString Extern::chefname="z";
QString Extern::servername="z";
QString Extern::managername="z";
int Extern::cur_finished_dish=0;
int Extern::cur_users=0;
QString Extern::man_chef_num="z";
QString Extern::man_ser_num="z";
int Extern::cur_server_to_desk=0;
int Extern::server_status=0;//服务员在线状态
int Extern::ctrl_menu_status=0;
